open_conext_engine_block_profile:
    resource: "@OpenConextEngineBlockProfileBundle/Resources/config/routing.yml"
    host:     "profile.{domain}"
    requirements:
        domain: ".*"
    prefix:   /

open_conext_engine_block_authentication:
    resource: "@OpenConextEngineBlockAuthenticationBundle/Resources/config/routing.yml"
    host:     "engine.{domain}"
    requirements:
        domain: ".*"
    prefix:   /

open_conext_engine_block_api:
    resource: "@OpenConextEngineBlockApiBundle/Resources/config/routing.yml"
    host:     "engine-api.{domain}"
    requirements:
        domain: ".*"
    prefix:   /
